### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ArthurPedroti** [AGF-Equipamentos/atgf#2]
### Boilerplates e estruturas inicias (13 dias)
- [x] Boilerplate frontend (20h) (4 dias)
- [ ] Boilerplate backend (42,5h) (9 dias)
### API Backend (10 dias)
- [ ] API ecommerce (30h) (6 dias)
### Frontend (44 dias)
- [ ] Componentes e paginas part 1 (110h) (22 dias)
- [ ] Componentes e paginas part 2 (110h) (22 dias)
### Autenticação e conexão protheus (21,5 dias)
- [ ] Autenticação (77,5h) (15,5 dias)
- [ ] API Protheus (30h) (6 dias)
### Testes e deploy (11 dias)
- [ ] Testes e melhorias (45h) (9 dias)
- [ ] Deploy e produção (10h) (2 dias)
